### ISSUE TITLE
I got 10 error when try to login.

### ISSUE THREAD

**Issue by nive745** [ionicthemes/ionic2-google-login#7]
I got 10 error from google plus when i tried to login and nothing happened.

 
![untitled](https://user-images.githubusercontent.com/17614227/52336609-59333800-2a2b-11e9-9836-8ded85743246.png)

**Comment by pawan-atl** [comment]
Hello, I am also getting the same error. Did you manage to resolve this issue?

**Comment by pavansai1122** [comment]
hello, me also getting same error. is there any solution??

**Comment by djabif** [comment]
Hi, can you please try this https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/243#issuecomment-245908012

**Comment by anshcena** [comment]
Error 10 : SHA error 
You need to use debug.keystore while app in development and generate the SHA key from machine from where the app apk or ios bundle is generated. If app installed from different machine then kindly generate the SHA key that is debug.keystore from that machine and create app.
Error 10 only deals with SHA improper or missing !

**Comment by anshcena** [comment]
> Hello, I am also getting the same error. Did you manage to resolve this issue?
https://github.com/ionicthemes/ionic-google-login/issues/7#issuecomment-544108788

**Comment by djabif** [comment]
Thanks @anshcena for sharing your solution!
